-- Lunar Graph Fraud Detection Tables
-- Migration: 003_lunar_graph.sql

-- Fraud Rings table
-- Stores detected fraud patterns and their details
CREATE TABLE IF NOT EXISTS fraud_rings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('opposite_trading', 'multi_account', 'ip_clustering', 'commission_pumping', 'timing_coordination')),
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  confidence DECIMAL(5,2) CHECK (confidence >= 0 AND confidence <= 100),
  entities TEXT[] DEFAULT '{}',
  exposure DECIMAL(12,2) DEFAULT 0,
  evidence JSONB DEFAULT '[]',
  ai_summary TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'investigating', 'resolved', 'false_positive')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lunar Alerts table
-- Stores fraud detection alerts
CREATE TABLE IF NOT EXISTS lunar_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('new_fraud_ring', 'risk_escalation', 'pattern_detected', 'entity_flagged', 'threshold_breach')),
  severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  title TEXT NOT NULL,
  description TEXT,
  entities TEXT[] DEFAULT '{}',
  fraud_ring_id UUID REFERENCES fraud_rings(id) ON DELETE SET NULL,
  acknowledged BOOLEAN DEFAULT FALSE,
  acknowledged_at TIMESTAMPTZ,
  acknowledged_by TEXT,
  ai_explanation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agent Analysis Logs table
-- Stores analysis results from each agent run
CREATE TABLE IF NOT EXISTS agent_analysis_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_type TEXT NOT NULL CHECK (agent_type IN ('alpha', 'beta', 'gamma')),
  agent_name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'error')),
  started_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  findings_count INTEGER DEFAULT 0,
  critical_count INTEGER DEFAULT 0,
  high_count INTEGER DEFAULT 0,
  summary TEXT,
  metrics JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Graph Snapshots table
-- Stores periodic snapshots of the knowledge graph for comparison
CREATE TABLE IF NOT EXISTS graph_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  total_nodes INTEGER NOT NULL,
  total_edges INTEGER NOT NULL,
  fraud_edges INTEGER DEFAULT 0,
  avg_risk_score DECIMAL(5,2) DEFAULT 0,
  clusters_detected INTEGER DEFAULT 0,
  node_distribution JSONB DEFAULT '{}',
  edge_distribution JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_fraud_rings_status ON fraud_rings(status);
CREATE INDEX IF NOT EXISTS idx_fraud_rings_severity ON fraud_rings(severity);
CREATE INDEX IF NOT EXISTS idx_fraud_rings_type ON fraud_rings(type);
CREATE INDEX IF NOT EXISTS idx_fraud_rings_created_at ON fraud_rings(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lunar_alerts_acknowledged ON lunar_alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_lunar_alerts_severity ON lunar_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_lunar_alerts_fraud_ring_id ON lunar_alerts(fraud_ring_id);
CREATE INDEX IF NOT EXISTS idx_lunar_alerts_created_at ON lunar_alerts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_analysis_logs_agent_type ON agent_analysis_logs(agent_type);
CREATE INDEX IF NOT EXISTS idx_agent_analysis_logs_created_at ON agent_analysis_logs(created_at DESC);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for fraud_rings updated_at
DROP TRIGGER IF EXISTS update_fraud_rings_updated_at ON fraud_rings;
CREATE TRIGGER update_fraud_rings_updated_at
  BEFORE UPDATE ON fraud_rings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS Policies
ALTER TABLE fraud_rings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lunar_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_analysis_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE graph_snapshots ENABLE ROW LEVEL SECURITY;

-- Allow all operations for authenticated users (in production, restrict this)
CREATE POLICY "Allow all for fraud_rings" ON fraud_rings FOR ALL USING (true);
CREATE POLICY "Allow all for lunar_alerts" ON lunar_alerts FOR ALL USING (true);
CREATE POLICY "Allow all for agent_analysis_logs" ON agent_analysis_logs FOR ALL USING (true);
CREATE POLICY "Allow all for graph_snapshots" ON graph_snapshots FOR ALL USING (true);

-- Comments
COMMENT ON TABLE fraud_rings IS 'Stores detected fraud patterns and rings identified by the Lunar Graph system';
COMMENT ON TABLE lunar_alerts IS 'Stores fraud detection alerts generated by the analysis agents';
COMMENT ON TABLE agent_analysis_logs IS 'Logs of each agent analysis run for audit and performance tracking';
COMMENT ON TABLE graph_snapshots IS 'Periodic snapshots of the knowledge graph for historical comparison';
